### ISSUE TITLE
UI issues on MacOS Big Sur (11.0.1)

### ISSUE THREAD

**Issue by mrcjkb** [violetlib/vaqua#1]
Hi,

I tested out vaqua on MacOS Big Sur 11.0.1 and I really like it so far.
I am aware that Big Sur is not yet officially supported, but I thought I would open this issue anyway, just in case you might be interested. I noticed the following two UI issues that block me from using VAqua at the moment:

- JTabbedPanes: The selected tabs are now painted white, with a white foreground. The same issue occurs with the regular Aqua LAF. I have found a (dirty) workaround for this, in which I create a `TabbedPaneUI` wrapper that adds a `ChangeListener` to correct the foreground of the selected tab and returns the VAqua tabbed pane UI in its factory method.

- JScrollPanes: The horizontal scroll bar does not appear and scrolling horizontally is not possible.

**Comment by cbfiddle** [comment]
Thanks for the report. A release for macOS 11 is in progress. The tabbed pane issue has been fixed.
I have not seen a problem with horizontal scroll bars.

**Comment by cbfiddle** [comment]
I'm now seeing odd scrolling behavior, but I see it in Finder, so I don't think it has anything to do with VAqua.
What I see when using a magic mouse is that one finger and two finger scrolling both work for vertical, but only one finger scrolling works for horizontal.

**Comment by mrcjkb** [comment]
Thanks for the update :)
I was able to fix the scrolling issues by setting the scroll pane type to "legacy" for the affected scroll panes (it does not affect all scroll panes and only happens in dark mode).
The tabbed pane issue is no longer present in version 9.
