### ISSUE TITLE
Disposed windows are retained and accessible through Frame.getFrames()

### ISSUE THREAD

**Issue by sreilly** [violetlib/vaqua#10]
In code added to forcibly apply the the VAqua theme to all open windows or frames I noticed that calling `java.awt.Frame.getFrames()` returns all frames ever constructed, including ones that are no longer visible or referenced, even if they have had `.dispose()` called on them.

Could Vaqua or JNR be keeping references to these windows or maybe not invoking some JVM cleanup code?

I've worked around this issue in my own code by having my top level frames clear their contents upon dispose() as that allows all of the downstream views and their references to be garbage collected, but that might not work for everyone.

**Comment by cbfiddle** [comment]
Any component could be the source of the problem because of the reference to the parent. Disposing has no impact on that.

Does this problem occur only when running VAqua?

Have you tried using VisualVM to identify where the references are held?
