### ISSUE TITLE
File chooser does not switch showing of hidden files when meta+shift+period is pressed

### ISSUE THREAD

**Issue by dpolivaev** [violetlib/vaqua#11]
When org.violetlib.aqua.fc.AquaFileChooserUI.KeyListenerAction.actionPerformed(ActionEvent) is called, it does not see period character because shift is pressed. On German layout it sees a colon `:`, on English layout it probably sees the greater character `>`. Therefore no case in the switch statement is matched and the action is not executed.

**Comment by cbfiddle** [comment]
Thanks for the report!

Interestingly, Cmd-Shift-Period works fine on a US keyboard. Perhaps a colon is considered an important character but greater-than is not?
I have a fix ready to include in the next release.
