### ISSUE TITLE
vaqua and jlink-ed JRE -- modular jar?

### ISSUE THREAD

**Issue by RBornat** [violetlib/vaqua#12]
I maintain an app (RBornat/jape on github) that uses Java for its GUI. I've recently converted it to use jlink in java 11 to build a minimal JRE so that I'm not at the mercy of my users' choices of JDK/JRE. I thought I'd try vaqua, because the look and feel in adoptJDK-11 is (IMHO) awful.

Your jar isn't a modular jar (no module-info.class). So it's a reasonable guess that it won't work with my JRE, and indeed it doesn't (see below) (probably because the modules you need aren't in my jlink-ed JRE). I hesitate to try to turn your jar into a module, because of all those dylibs (I don't know how to find things in modules with a classloader).

Help? And I apologise if this is a naive question.

---------------------------------

I'm using vaqua9; the launch command is 

    ./Contents/Java/jre/bin/java \
      -Dapple.awt.rendering=quality -Dapple.laf.useScreenMenuBar=true -Dapple.awt.antialiasing=true -Dapple.awt.showGrowBox=true -DNSHighResolutionCapable=true -Duk.org.jape.AppPackage=$APP_ROOT \
      -Xbootclasspath/a:./Contents/Resources/VAqua9.jar \
      -m uk.org.jape/uk.org.jape.Jape $@

The code in Jape is 

    if (onMacOSX) {
                    try {
                        UIManager.setLookAndFeel("org.violetlib.aqua.AquaLookAndFeel");
                    }
                    catch (ClassNotFoundException | InstantiationException
                            | IllegalAccessException
                            | UnsupportedLookAndFeelException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                }

and the error I receive is

    Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: org/violetlib/aqua/AquaUtils.registerWindowChangedAppearanceCallback(Lorg/violetlib/aqua/AquaUtils$WindowAppearanceChangedCallback;)V
	at org.violetlib.aqua.AquaUtils.<clinit>(Unknown Source)
	at org.violetlib.aqua.AquaNativeSupport.reportError(Unknown Source)
	at org.violetlib.aqua.AquaNativeSupport.loadNativeSupport(Unknown Source)
	at org.violetlib.aqua.AquaNativeSupport.load(Unknown Source)
	at org.violetlib.aqua.AquaLookAndFeel.isSupportedLookAndFeel(Unknown Source)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:572)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:633)

I suspect I'm doing it wrong ... Proba

**Comment by cbfiddle** [comment]
You have found at least one bug. AquaNativeSupport is trying to report an error, but the class it uses for that depends upon a native library so it gets an error. Oops.

If you can run in a debugger, break on reportError to see the message.

The problem appears to be in finding or loading the dynamic libraries.

Can you tell if it is able to copy the dynamic libraries to temp files?

If you can extract the dynamic libraries to files, then try using java.library.path.

  Alan

**Comment by RBornat** [comment]
I did look at trying to generate module-info, but I'm a bit naive at that too:

    richard@Richard-Bornats-Mac-Mini MacOSX % jdeps --generate-module-info . Vaqua9.jar
    Missing dependence: ./Vaqua9/module-info.java not generated
    Error: missing dependencies
       org.violetlib.aqua.Aqua8MappedMultiResolutionImage -> sun.awt.image.MultiResolutionImage                 JDK removed internal API
       org.violetlib.aqua.Aqua8MappedMultiResolutionImage$MyVariantMapper -> sun.awt.image.MultiResolutionImage                 JDK removed internal API
       org.violetlib.aqua.Aqua8MultiResolutionImage       -> sun.awt.image.MultiResolutionImage                 JDK removed internal API
       org.violetlib.aqua.Aqua8MultiResolutionImage2      -> sun.awt.image.MultiResolutionImage                 JDK removed internal API
       org.violetlib.aqua.Java8Support                    -> sun.awt.image.MultiResolutionImage                 JDK removed internal API
       org.violetlib.aqua.Java8Support                    -> sun.swing.SwingUtilities2$AATextInfo               JDK removed internal API
       org.violetlib.jnr.impl.JNR8MultiResolutionImage    -> sun.awt.image.MultiResolutionImage                 JDK removed internal API

**Comment by RBornat** [comment]
You asked me to make the dynamic libraries visible. Jape prints System.Properties(), helpfully. I put them in the jre lib, which is on all the paths in there, including java.library.path

    java.library.path=/Users/richard/gitrepositories/japery/jape/distrib/MacOSX/build/Jape.app/Contents/Java/jre/lib/compressedrefs:/Users/richard/gitrepositories/japery/jape/distrib/MacOSX/build/Jape.app/Contents/Java/jre/lib:/usr/lib

Clearly, /Users/richard/gitrepositories/japery/jape/distrib/MacOSX/build/Jape.app/Contents/Java/jre/lib is on the library path, and they are there in the filestore too (I seem to have got them all):

    richard@Richard-Bornats-Mac-Mini MacOSX % ls /Users/richard/gitrepositories/japery/jape/distrib/MacOSX/build/Jape.app/Contents/Java/jre/lib
    compressedrefs			java_ko.properties		jvm.cfg				libjsig.dylib			libvappearances.dylib
    fontconfig.bfc			java_pl.properties		libVAquaRendering.dylib		libjsound.dylib			libvaqua.dylib
    fontconfig.properties.src	java_pt_BR.properties		libawt.dylib			libkeywindowpatch.dylib		libverify.dylib
    j9vm				java_ru.properties		libawt_lwawt.dylib		liblcms.dylib			libwindowstylepatch.dylib
    java.properties			java_sk.properties		libcrypto.1.1.dylib		libmlib_image.dylib		libzip.dylib
    java_ca.properties		java_sl.properties		libfontmanager.dylib		libnet.dylib			modules
    java_cs.properties		java_tr.properties		libfreetype.dylib		libnio.dylib			options.default
    java_de.properties		java_zh.properties		libharfbuzz.dylib		libosx.dylib			psfont.properties.ja
    java_es.properties		java_zh_CN.properties		libjava.dylib			libosxapp.dylib			psfontj2d.properties
    java_fr.properties		java_zh_TW.properties		libjavajpeg.dylib		libosxsecurity.dylib		security
    java_hu.properties		jli				libjawt.dylib			libosxui.dylib			server
    java_it.properties		jrt-fs.jar			libjimage.dylib			libprefs.dylib			tzdb.dat
    java_ja.properties		jspawnhelper			libjncrypto.dylib		libsplashscreen.dylib

But I get the same error:

    Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: org/violetlib/aqua/AquaUtils.registerWindowChangedAppearanceCallback(Lorg/violetlib/aqua/AquaUtils$WindowAppearanceChangedCallback;)V

Hmm?

**Comment by cbfiddle** [comment]
Those are only used in JDK 8, should not be a problem.

**Comment by cbfiddle** [comment]
That error message just means that VAqua tried to log an error and failed, as I mentioned before.

You will need to use a debugger to find the actual error message.

  Alan

**Comment by RBornat** [comment]
Ah. I thought it had refused to build the module-info file. I’ll check. Thanks. 

R

**Comment by RBornat** [comment]
What I meant was that it wasn’t enough to make the libraries available. I’ll try again today to make a module, and see if that works. 

Richard
