### ISSUE TITLE
JRadioButton behaves unexpected

### ISSUE THREAD

**Issue by frankb33** [violetlib/vaqua#13]
I was really glad when I stumbled about VAqua. I regretted when QuaQua wasn't maintained further so I was greedy to give it a try. Unfortunately I nearly immediately stumbled over the following issue. I use JRadioButtons with Images for the selected/unselected state which looks on Linux/Win/Mac and with System, Metal, Nimbus, Quaqua, FlatLaf, Substance, Jyloo like this (here System):
<img width="256" alt="System" src="https://user-images.githubusercontent.com/36103811/127714937-2bba8b7a-f5c2-4e05-9be2-d935767d8885.png">

With VAqua and the default it looks like this:

<img width="174" alt="VAqua_default" src="https://user-images.githubusercontent.com/36103811/127714818-4c6c96c5-e62e-453a-9a80-c6390dd399b1.png">

when I use btn.putClientProperty("JButton.buttonType", "icon");  it shows animated borders but no image:
<img width="192" alt="VAqua_icon" src="https://user-images.githubusercontent.com/36103811/127715080-80fe811e-64a4-4e4d-ace7-42e78d889b74.png">

Do you have any suggestion? I would love to use Vaqua.

I tested it with 10.13 and Java 8 but can test it with 10.14/15 11 and Java 11 or 16 if you wish.

**Comment by cbfiddle** [comment]
Have you tried using JToggleButton?

**Comment by frankb33** [comment]
Wow, what a fast answer, thanks a lot. I Just checked it. I was astonished that the source of the JRadioButton has no real additional functionality compared to JTogglebutton,  so I thought that might work but it looked ugly first:
<img width="183" alt="withToggleButton" src="https://user-images.githubusercontent.com/36103811/127719082-06197a96-adb9-4d1c-b8d3-5c8d3d1ad4e1.png">

With 
btn.setFocusable(false);
btn.setBorder(javax.swing.BorderFactory.createEmptyBorder());
I get rid of the unwanted focus indicator and the unwanted border so this worked as wanted. Thanks a lot.

**Comment by cbfiddle** [comment]
Buttons are not normally focusable on macOS unless the user specifically requests it, so ordinarily one should not need to set the focusability, and doing so is a bad idea because it prevents the user from making them focusable.

The problem might have arisen if you changed the look and feel while the program was running?

The focus ring is not painted using a border, so it should not be necessary to set the border, but it doesn’t hurt to do so.

**Comment by frankb33** [comment]
"The problem might have arisen if you changed the look and feel while the program was running?"
I load VaQua at runtime. On Linux/Windows  changing the L&F  belonged always to the program. To support dark mode I want to give the MacOS user the choice too.

"The focus ring is not painted using a border, so it should not be necessary to set the border, but it doesn’t hurt to do so."
For whatever reason I see the border around the icon only Togglebutton, but no issue, setting an empty border looks as expected.

I had two crashes in native code, but can't reproduce it anymore. Maybe it's helpful so I attached the hs_err_pid files
[hs_err_pid10060.log](https://github.com/violetlib/vaqua/files/6949528/hs_err_pid10060.log)
[hs_err_pid10952.log](https://github.com/violetlib/vaqua/files/6949529/hs_err_pid10952.log)

**Comment by cbfiddle** [comment]
I’m not saying that you shouldn’t change the LAF at run time, just that switching at run time is not perfect and may require additional initialization, as you discovered.

I would suggest testing with the “Use keyboard navigation to move focus between controls” system preference enabled. (It might have a different name in older macOS releases.)

I don’t see anything familiar in the log files.
