### ISSUE TITLE
Failed to load window patches

### ISSUE THREAD

**Issue by Zaprit** [violetlib/vaqua#16]
When starting my application this error occurs:
```
KeyWindowPatch: Unable to load library: /private/var/folders/05/dhxxxqw93h5380mqq718gpk80000gn/T/libkeywindowpatch7025539328960261627.dylib: dlopen(/private/var/folders/05/dhxxxqw93h5380mqq718gpk80000gn/T/libkeywindowpatch7025539328960261627.dylib, 0x0001): symbol not found in flat namespace '_OBJC_CLASS_$_AWTToolkit'
WindowStylePatch: Unable to load library: /private/var/folders/05/dhxxxqw93h5380mqq718gpk80000gn/T/libwindowstylepatch8964088340466037946.dylib: dlopen(/private/var/folders/05/dhxxxqw93h5380mqq718gpk80000gn/T/libwindowstylepatch8964088340466037946.dylib, 0x0001): symbol not found in flat namespace '_OBJC_CLASS_$_AWTWindow_Normal'
```
this is on an M1 macbook air running macOS monterey

**Comment by cbfiddle** [comment]
Hmm. I have not seen that before.

It looks like it could be a problem in the order of loading or initialization.

Are you doing anything to get AWT/Swing etc to load and initialize before trying to load VAqua?

**Comment by Zaprit** [comment]
It turns out that it will fail less or not at all by changing out the jvm. Though I am not doing any weird I it code that I know of.

**Comment by cbfiddle** [comment]
Intermittent failures suggest a threading issue.

Are you using SwingUtilities.invokeLater to run your initialization code?

**Comment by Zaprit** [comment]
Yes, should I not be doing so?

**Comment by cbfiddle** [comment]
Yes, that is what you should be doing.

Can you use breakpoints to find out what is causing VAqua to be loaded and if it is being loaded either too soon or on the wrong thread?

**Comment by Zaprit** [comment]
VAqua is loaded by the UIManager.setLookAndFeel, I also tried it with the one that just takes a LAF class rather than doing it via reflection, to no avail. What makes me wonder though is why it works fine on java 16, but fails on 11 or 8

**Comment by cbfiddle** [comment]
The key window patch should be loaded only for Java 8, 9, or 10.
If you are getting an error loading it on Java 11 or 16, something may be wrong with the detection of the Java version.

This program works for me on jdk1.8.0_162 and jdk-11.0.2.jdk.



public class TestVAquaLoading
{
    public TestVAquaLoading()
    {
        try {
            UIManager.setLookAndFeel("org.violetlib.aqua.AquaLookAndFeel");
        } catch (Exception ex) {
            System.err.println("setLookAndFeel failed: " + ex);
        }

        JFrame fr = new JFrame();
        fr.setBounds(100, 100, 200, 200);
        fr.setVisible(true);
    }

    public static void main(String[] args)
    {
        SwingUtilities.invokeLater(TestVAquaLoading::new);
    }
}

**Comment by Zaprit** [comment]
Yeah, it turns out that my init code was just a mess, rewrote that and it works great. Thanks for your help.
