### ISSUE TITLE
Putting ColorUIResource()  into UIDefaults causes RGB 0,0,0 to later default into swing components

### ISSUE THREAD

**Issue by yogi1967** [violetlib/vaqua#17]
If you set a color using ColorUIResource() into UIManager's UIDefaults then you get RGB values of 0,0,0 returned into swing component's default Colours. 

Using ColorUIResource() within UIDefaults on other platforms or LaFs works fine. But not on VAQua. 

Conversely, setting Color() works fine. 

defaults = UIManager.getDefaults()
defaults.put("Label.foreground", ColorUIResource(74,74,74))
l = JLabel("test")
c = l.getForeground()

c wrongly returns:
javax.swing.plaf.ColorUIResource[r=0,g=0,b=0]

if I swap the code above to put Color(74,74,74) into defaults, then c correctly returns:
java.awt.Color[r=74,g=74,b=74]

**Comment by cbfiddle** [comment]
Unlike other LAFs, VAqua generally does not use the UI defaults for colors. But it does allow you to override the default appearance by installing a Color (but not a UIResource) in the component. The fact that the Color is not a UIResource is what allows VAqua to recognize that the application wants a different color than the VAqua default color.

That should explain why Color and ColorUIResource have different effects.

I’m not sure about the getForeground method returning unexpected results. I don’t think the LAF is involved. Are you sure your tests are doing what you think they are?

**Comment by yogi1967** [comment]
Thanks for the reply. Yes, the test is very simple. Put a Color into UIDefaults and then create a JLabel instance and getForeground is correct. Stick a ColorUIResource into the same UIDefaults and then a new JLabel getForeground returns 0,0,0

Anyway, I think you've been clear to use Color and not ColorUIResource. 

Thanks.
