### ISSUE TITLE
AquaNativeSupport error

### ISSUE THREAD

**Issue by vewert** [violetlib/vaqua#18]
When running my application using VAqua10, I get the following error displayed to console:

`AquaNativeSupport: Unable to load library libvaqua.dylib: Can't load library: /var/folders/zh/4wvt7r9n6_vgfxdhk3qx96cr0000gn/T/libvaqua1061541747682913295.dylib`

and the following Exception is thrown when setting the look and feel:

`javax.swing.UnsupportedLookAndFeelException: VAqua release 10 (build 2021-09-13T18:59:18Z) not supported on this platform`

I'm not sure what I am doing wrong.

Environment:
macOS 11.6.5 (Silicon)
Java 17.0.3

**Comment by cbfiddle** [comment]
It appears that you are running on an Apple Silicon processor.
You’ll need to use VAqua 11 and follow the instructions on the web site regarding the JavaNativeFoundation framework.

**Comment by vewert** [comment]
Thanks for the prompt reply. 
Where can I get VAqua 11, the website and MavenCentral only seem to have up to VAqua 10.

**Comment by cbfiddle** [comment]
Right you are!

I think then most likely the issue is getting a JavaNativeFoundation framework that supports ARM.

https://violetlib.org/share/universalbinaries.html

build from
https://github.com/apple/openjdk/tree/xcodejdk14-release/apple/JavaNativeFoundation <https://github.com/apple/openjdk/tree/xcodejdk14-release/apple/JavaNativeFoundation>
or find it in Xcode

**Comment by vewert** [comment]
Thanks. I tried reading the documentation you mentioned but am still confused. How do I bundle the Framework (once I figure out how to get it) with my app? I am using Gradle and jlink/jpackage to build and produce my app.

Also I get a similar error when running on Intel64.

**Comment by cbfiddle** [comment]
I use jpackage only to create an image, which I can then modify and code sign as needed.

Regarding the library loading error, I can only make some suggestions:

* If you run java or the launcher from Terminal, you may see additional error messages.

* Use otool -l on the native library to see what it depends on, and make sure those dependencies are present or available using DYLD_FRAMEWORK_PATH.

* Just in case, use code sign to verify that the native library is not damaged.

**Comment by vewert** [comment]
I got it working for Intel64, by modifying the info.plist and adding the DYLD_FRAMEWORK_PATH environment variable, but don't understand how to get it to work for silicon: Where do I get, and how to a bundle the silicon Framework, into the app?

**Comment by cbfiddle** [comment]
You can build the framework from source using the URL I gave you, or /usr/bin/find the actual framework inside Xcode.app, then copy it into your bundle and set DYLD_FRAMEWORK_PATH to include that location.
