### ISSUE TITLE
Striped table should start with white rather than grey

### ISSUE THREAD

**Issue by karlvr** [violetlib/vaqua#21]
Like this:

<img width="708" alt="image" src="https://user-images.githubusercontent.com/1086005/174760961-ed6ed1b6-1d35-43e3-862e-8cc0d91d12a1.png">

**Comment by cbfiddle** [comment]
What happens in dark mode?

**Comment by karlvr** [comment]
Here is Finder in Dark Mode

<img width="708" alt="image" src="https://user-images.githubusercontent.com/1086005/174886277-b97de676-59d3-413f-9e1a-51ba93dd87af.png">

I think it renders OK in VAqua actually. It does reveal that I've neglected my app in Dark mode for a while.

**Comment by cbfiddle** [comment]
But what happens after your fix?

**Comment by karlvr** [comment]
Before my fix the first row was striped rather than being white. After my fix the first row is white and second row striped, and in dark mode it now looks like the finder above.

<img width="841" alt="image" src="https://user-images.githubusercontent.com/1086005/174976590-e828c0d0-663b-4842-8f77-9eefc943123f.png">
<img width="843" alt="image" src="https://user-images.githubusercontent.com/1086005/174976703-47cb45f7-222f-4d99-b15e-99b9db59c57a.png">

**Comment by cbfiddle** [comment]
Thanks.

It looks to me like lists and trees have the same issue.

If so, wouldn’t it be better to swap the colors instead of changing the code?

**Comment by cbfiddle** [comment]
This change is appropriate only for macOS 11 and later.

On earlier systems, the first row is striped.

**Comment by karlvr** [comment]
@cbfiddle ah, I was just wondering that. OK, I will update the PR!
