### ISSUE TITLE
Vibrant title bar is too translucent

### ISSUE THREAD

**Issue by karlvr** [violetlib/vaqua#23]
I am experimenting with a vibrant title bar and trying to achieve the look of various native windows on macOS Monterey. They appear to have vibrant title bars but with an only slightly transparent white fill on the title bar. I have successfully achieved this look by customising the colours in `SystemColors` when the view is vibrant, but I'd like to check 1) that I haven't missed the right way to do this and 2) whether this is something that you'd be interested in receiving a contribution on, because I'll probably need your input to make sure I get it right in the general case!

**Comment by cbfiddle** [comment]
Well, you can only approximate a vibrant look by using a translucent color. I guess I would have to see it in action to determine if it is an improvement.

I don’t understand the description of your change, so I cannot advise you on its correctness.

My sense is that the right long term strategy is to use native title bars, but that would be a big project.

**Comment by karlvr** [comment]
@cbfiddle thanks for your response; I'm still using the vibrancy, but just changing the colour that gets laid over it. I think pretty sure we're doing that in the existing code... it's just that we use quite a lot of alpha transparency so more of the vibrancy shows through...

I'll post some screenshots in due course.

**Comment by cbfiddle** [comment]
vibrantTitleBar is not an option for using a vibrant title bar, it is the name of a vibrant material that AppKit uses for title bars.
VAqua does not use it.

**Comment by karlvr** [comment]
Oh, doh, I was setting:

```java
getRootPane().putClientProperty("Aqua.backgroundStyle", "vibrantTitleBar");
```

and hoping that my whole root pane including the title bar of my window would get that vibrancy. I do get vibrancy, but is it not doing what I was hoping for?

I have approximated how native macOS title bars look by apply translucent white over the top of the the translucency (that's what I was referring to above), so I still have the vibrancy, just toned down.

**Comment by cbfiddle** [comment]
So, is there an action item here?

Are you using one of the special window styles?

Is the title bar the problem or is it the toolbar?

**Comment by cbfiddle** [comment]
Where in the code is a color painted over the vibrant material?
