### ISSUE TITLE
Inset striped rows's rounded-rect should be drawn anti-aliased

### ISSUE THREAD

**Issue by karlvr** [violetlib/vaqua#24]
I've noticed that the rounded-rect that's drawn for the inset striped table rows isn't drawn with anti-aliasing. I've set the rendering hit around the `g.fillRect(r)`s and it looks heaps better.

I also increased the corner radius from 8 to 10, which I thought looked more like what I was seeing, but I'm not so sure about that.

Am I on the right track? Would you like a PR for some anti-aliasing for those rounded-rects?

**Comment by cbfiddle** [comment]
Interesting. I suspect you are correct regarding the corner radius.
A PR sounds good.
