### ISSUE TITLE
Unwanted cursor homing after using a dead-key

### ISSUE THREAD

**Issue by VBoudry** [violetlib/vaqua#25]
I am a secondary user of VAqua, as a user of FreePlane (https://docs.freeplane.org/home.html), and I am a fan of the VAqua interface which brings a decent OSX file-chooser.

But as French speaker (and typer) a small bug in the library, or in the implementation ?, makes it barely usable :
 - in a standard text window, whenever I use a dead key, such as “alt-e e” (to get a “é”), I get the requested character, but the next key is ignored, and the cursor jumps to the beginning of the text field.
 - in the file chooser, I observe the same behaviour, except that the second key is not ignored.
So I have to force myself to move the cursor back after every accented character.

I am no programmer in Java, so it would take me too much time to set up an environment to play around, but the bug can be easily found by:
 - installing the latest version of freeplane (https://sourceforge.net/projects/freeplane/), 
 - opening the preference pane (Meta-,) and in the "Appearance" pane change the default "Look and Feel" to VAqua", closing
 - making a new map (Meta-N), and by double clinking on the central node, editing it.  Type "abcd alt-e e 123"
 - Meta-S brings in the file chooser. Type the same sequence.
The developer is very responsive, but send me back to you on this specific issue.

Have a nice day,
Vincent Boudry.

**Comment by cbfiddle** [comment]
That bug has been fixed in the sources on github, but is not yet in a packaged release.

  Alan

**Comment by VBoudry** [comment]
Thanks !
When do you plan the next release ?

**Comment by cbfiddle** [comment]
The fix is available in release 11.
