### ISSUE TITLE
VAQua is creating and holding on to changeListeners...  VAQua version 11

### ISSUE THREAD

**Issue by yogi1967** [violetlib/vaqua#35]
We have spent a long time debugging code to find out why our java class instances in memory are not dying and then are not being garbage collected after we have removed all references to them. It's critical they 'die'.. (i.e. they hold open and access file objects). Using VisualVM we have determined that VAQua is creating and holding onto change listeners on many swing objects (that we have already fully dereferenced). These listeners can be found in:

org.violetlib.aqua.OSXSystemProperties.changeListeners
org.violetlib.aqua.AquaAppearances.changeListeners

VisualVM reports these as the top of the tree leading to GC Root. Initially it looked like the key problems were AquaFullKeyboardFocusableHandler listeners holding onto a JButton instance (which was very odd).. Using Reflection, when we called listener.dispose() on all those, then the problem 'jumped' (or was identified) to the AquaScrollPaneUI listeners.. So we just called .clear() on the whole change listener list. The problem then moved onto the AquaAppearances changeListeners. After calling .clear() on those, then all the locked swing objects were released, were garbage collected, and thus, all our key class instanced were also released..

Clearly we do not want to do this. So can the code be fixed so that perhaps these change listeners are all WeakReferences()?

NOTE: This does not happen with other LAFs, only VAQua..

Many thanks

**Comment by cbfiddle** [comment]
I'm not seeing any difference between VAqua and the Aqua look and feel regarding listeners.
Listeners are removed when a Swing component UI is uninstalled.
They are not removed when a Swing component is garbage collected or disposed.
(I am unaware of any support for garbage collecting a Swing component hierarchy, which seems odd.)

Can you explain how you are removing all references to your instances?
Does that include references from Swing components?

**Comment by yogi1967** [comment]
In simple terms. 
- JFrame. Override .dispose(). Set JMenuBar to null. Also call getContentPane().removeAll(). Set various added fields to null. .super() dispose. 
- On other non swing classes that hold a reference to the frame, set to null. 
- where there are other custom listeners, remove those. 

As mentioned, using standard Aqua, these issues do not exist. So somehow, VAQua is holding onto these changeListeners and that’s stopping the swing components from GC’ing.

**Comment by cbfiddle** [comment]
I think you are correct about Aqua. It's listeners are all registered on components, so they will be GC'ed when the components are. I'll look into trying to fix this.

**Comment by yogi1967** [comment]
Thank you. It's a real pain as it is. Will be very grateful.

**Comment by yogi1967** [comment]
FYI. There's also a pull request #34 that's for this same app. Is it also possible to accept that too?

https://github.com/violetlib/vaqua/pull/34

Thanks.

**Comment by cbfiddle** [comment]
I have a possible fix, if you care to try it out.
Link is valid for 7 days.
https://we.tl/t-Lo4jIfZJfG

**Comment by yogi1967** [comment]
Thanks. Nope the problem has moved, but is not fixed.. See screenshots (with original VA11 and your fixed build). The problem has moved from:
`static changeListeners in o class org.violetlib.aqua.OSXSystemProperties : OSXSystemProperties`
<img width="909" alt="old_va11" src="https://github.com/violetlib/vaqua/assets/22958485/0bd19501-af59-4f72-ab19-04f94a6eece7">

to:
`static components in o class org.violetlib.aqua.SystemPropertyChangeManager : SystemPropertyChangeManager`
<img width="911" alt="fixed_va" src="https://github.com/violetlib/vaqua/assets/22958485/b20ae226-9c56-4176-a51f-bd5c164ef0a4">

Is there another (similar) problem to address..?

Thanks for your help..

PS - Is there a method call I can make to know I am on the fixed build vs the original build?

**Comment by cbfiddle** [comment]
I'm using a WeakHashMap, so it might be necessary to force a gc to reset the weak links.

VAquaClient has a method that might work for identifying a fixed build.
https://violetlib.org/vaqua/clientlibrary.html

**Comment by yogi1967** [comment]
Yup - I have been forcing GC first

**Comment by cbfiddle** [comment]
The only thing I can think of is that there are other references to these objects somewhere.

**Comment by yogi1967** [comment]
As mentioned before, does not happen using standard / other LaF(s)....?

I will keep playing....

**Comment by cbfiddle** [comment]
Try this:
https://we.tl/t-Xlafzt5Xru

**Comment by yogi1967** [comment]
Will do. What did you change? Thx.

**Comment by cbfiddle** [comment]
Improper use of WeakHashMap.

**Comment by yogi1967** [comment]
Ah yes... gotcha... will test again when I can. Thx.

**Comment by yogi1967** [comment]
YUP - That works!! The objects are no longer being held captive and are dying with System.gc().. THANK YOU. 
Would it also be possible to accept pull request https://github.com/violetlib/vaqua/pull/34 (that's for this same app I use) too?
When do you think this fix will be in a published build?
Many thanks

**Comment by cbfiddle** [comment]
I think the fix for #34 is in the JAR you have.

**Comment by yogi1967** [comment]
Thanks!

**Comment by cbfiddle** [comment]
Actually, I'm not sure about the previous JAR, but it should be in this one.
https://we.tl/t-GXoMjlFTkW

**Comment by yogi1967** [comment]
When do you think there will be an 'official' build of this jar (with these fixes)? As the app developer won't be able to use it until then? Many thanks.

**Comment by yogi1967** [comment]
Hi, when do you think there will be an 'official' build of this jar (with these fixes)? As the app developer won't be able to use it until then? Many thanks.

**Comment by yogi1967** [comment]
I think I have found another VAQua issue that does NOT occur with the default LAF.

Randomly a dereferenced JPanel is getting locked by:
(JMenuBar>JMenu>AbstractAction linked to a JFrame)
> JRootPane >> JLayeredPane >> AquaFocusRingPainter >> **AquaFocusRingManager**

The application does not (knowingly) use AquaFocusRingPainter/Manager and it does not set the "Aqua.useFocusRing" property anywhere..

Using VisualVM, I can see that after all references to this JFrame/JPanel have been deleted, it remains locked by the above. Refer screenshot.. It's the reference back to GCRoot. I can reproduce this.

As mentioned, this does NOT occur when I switch to the default non-VAQua theme.

Thoughts?

Many thanks

<img width="974" alt="AquaFocusRingManager ref lock" src="https://github.com/violetlib/vaqua/assets/22958485/b9746895-49bb-4eeb-abe4-a2e46c4b27c1">

**Comment by cbfiddle** [comment]
I have an idea of what might be causing this problem.
Please try this:
https://we.tl/t-Hj5X7rvAb9

**Comment by yogi1967** [comment]
Thanks. Will do. Can you give me a hint of what you changed?

**Comment by cbfiddle** [comment]
Failed to implement a detached() method that removes the overlay painter component.

**Comment by yogi1967** [comment]
Hi, just tested. Sorry to report that issue still exists. VisualVM from latest test using latest jar

<img width="1013" alt="Screenshot 2023-09-23 at 18 37 55" src="https://github.com/violetlib/vaqua/assets/22958485/c64f155c-f08b-4b43-8c1e-7cf55e32ff1a">

**Comment by yogi1967** [comment]
(it would be really handy if these jar files (that I am testing) are able to print a version/build to std err. (for debug purposes)... possible?

**Comment by cbfiddle** [comment]
org.violetlib.aquaAquaLookAndFeel.showVersion() does that

**Comment by cbfiddle** [comment]
Another try:
https://we.tl/t-siP4QXiKtz

**Comment by yogi1967** [comment]
Thanks for the org.violetlib.aquaAquaLookAndFeel.showVersion() tip - that's great!

YES - it looks like your latest fix addresses this issue too - thanks.. What was the final fix you made? Many thanks....

**Comment by yogi1967** [comment]
When do you think it might become a published (official) build..?

**Comment by yogi1967** [comment]
Uh oh... Sorry, it may not be 100% fixed.. It's definitely better, but after quite a hammering on the app, the locked references came back in the same place.. See latest ScreenShot.. I do see however that the lock has moved. It's no longer up to AquaFocusRingManager, it seems to be up to change listeners... Thoughts?

<img width="1046" alt="Screenshot 2023-09-26 at 13 39 19" src="https://github.com/violetlib/vaqua/assets/22958485/9a2c9f08-c96f-4a9a-a55e-2ccd0d193335">

**Comment by cbfiddle** [comment]
Have you confirmed that this problem does not happen using Aqua LAF?

**Comment by yogi1967** [comment]
I knew that was coming. I'll attempt to prove/disprove. Thx.

**Comment by yogi1967** [comment]
I cannot reproduce it using standard LAF, but I can get it to appear using VAqua... Oddly the lock changes slightly. Another one attached 
<img width="1053" alt="viewhomeaction2" src="https://github.com/violetlib/vaqua/assets/22958485/f93bedcb-83e4-4407-949b-fe5e49fa1037">

**Comment by cbfiddle** [comment]
I'm not sure what to do about this, as nothing looks familiar.

**Comment by yogi1967** [comment]
Let me do some further testing...

**Comment by cbfiddle** [comment]
The fixes have been released in version 12.

**Comment by yogi1967** [comment]
Fantastic. Thanks.

**Comment by yogi1967** [comment]
Hmm. We are getting this message now with the new vaqua12

`...libVAquaRendering.dylib' (slice is not page aligned, fat file, but missing compatible architecture (have 'x86_64,arm64', need 'x86_64h' or 'x86_64')
`

It doesn't happen with vaqua11. Any ideas?

**Comment by cbfiddle** [comment]
No idea.

I don’t see anything on the web that explains this.

Could the file have been corrupted?

**Comment by yogi1967** [comment]
None issue - bad (internal) build. Thanks for replying. Sorry to bother you!
