### ISSUE TITLE
Mouse events's `y` is 3px too much

### ISSUE THREAD

**Issue by karlvr** [violetlib/vaqua#37]
This is a weird one, so I'm posting it while I'm investigating it. I wonder if anyone else is seeing it? I am seeing the `y` value on `MouseEvent`s reported consistently about 3 pixels much... I see this when selecting table rows, when rolling over buttons, in a toolbar, in the window body...

I'm not sure whether I've done something to my app or not. Is anyone else seeing this?

**Comment by karlvr** [comment]
I don't want to sound like a conspiracy theorist, but I've disabled VAqua and I think my mouse events still need `3` subtracted off their `y`. I'm running a reasonably recent Java 17, but I'll upgrade it just to be sure.

**Comment by cbfiddle** [comment]
Are you implying that users see this problem? I have not noticed anything like that.

**Comment by karlvr** [comment]
@cbfiddle yeah, I can see it in toolbar buttons and on table rows... if I move the mouse to the bottom of the table row (and zoom in if necessary) I can see the pointer is over the previous row but clicking hits the next row!

It seems like it's me, somehow, so I'll keep going down this rabbit hole!

**Comment by cbfiddle** [comment]
I suspect this is related to a window style and a possible change to the height of the standard title bar.
Are you using a special window style?

**Comment by karlvr** [comment]
@cbfiddle thank you for your attention on this. I've been on a journey, mostly because it turns out you [can't build OpenJDK on macOS Sonoma currently](https://github.com/Homebrew/homebrew-core/issues/150824)!

Anyway, the 3px was of course pilot error... I was looking at the white tip of the pointer, not the black tip! I was also chasing some issues with `JTableWithMargins` and `InternalTableWithMargins` not accounting for the vertical margin in `rowAtPoint` (I'll submit a PR once I'm sure)...

**Comment by cbfiddle** [comment]
I was able to build the JDK on macOS 14 by using the macOS 13 SDK.
Install Xcode 14, which contains the macOS 13 SDK.
Either xcode-select it or configure the build with --with-toolchain-path=/Applications/Xcode14.app/Contents/Developer/usr/bin.

**Comment by karlvr** [comment]
@cbfiddle heh yeah I decided not to download that but I put in some swizzling on that bad method and that worked around it for now :-D
