### ISSUE TITLE
JTextFields randomly get into a bad selection state causing keyboard input problems

### ISSUE THREAD

**Issue by yogi1967** [violetlib/vaqua#40]
Latest VAQua build
Java21 (but also issue on earlier builds)
macOS (many versions).
Does NOT occur on other LaF's

REFER VIDEO

https://github.com/violetlib/vaqua/assets/22958485/722c6551-7357-4573-b67f-b05d7bd6560b

Randomly, you go to type and you find that there is only one character and this is selected/highlighted. If you try to type then only the last letter is entered and stays selected. The only way to type is to cursor left, type one letter, and repeat (i.e. slowly and backwards). To fix you close the form and try again, or click on a combobox and click back.

The app's lead developer has suggested that this is likely caused / related to setting the caret position when the text is selected. This is all managed by vaqua.

**Comment by cbfiddle** [comment]
I can't really comment on this without knowing what other tricky things your code might be doing, if the previous issue is any indication. If you are not doing anything tricky, then it should be possible to demonstrate the problem in a simple test program.

**Comment by yogi1967** [comment]
The code on this is very simple....

field = JTextField() 

etc

It's random.. Whenever you want to reproduce it, you can't...

Does VAQua do something with caret position and text selection?

**Comment by yogi1967** [comment]
It just happened again... Here was the code:

```
    class MyKeyAdapter(KeyAdapter):
        def keyPressed(self, evt):
            if (evt.getKeyCode() == KeyEvent.VK_ENTER):
                evt.getSource().transferFocus()

    class MyJTextField(JTextField):

        def __init__(self, *args, **kwargs):
            self.maxWidth = -1
            self.fm = None
            self.minColWidth = kwargs.pop("minColWidth", None)
            super(self.__class__, self).__init__(*args, **kwargs)
            self.setFocusable(True)
            self.addKeyListener(MyKeyAdapter())

        def updateUI(self):
            super(self.__class__, self).updateUI()
            setJComponentStandardUIDefaults(self)

        def getMinimumSize(self):
            dim = super(self.__class__, self).getMinimumSize()
            if self.minColWidth is None: return dim
            if (self.fm is None):
                f = self.getFont()
                if (f is not None):
                    self.fm = self.getFontMetrics(f)
            strWidth = 35 if self.fm is None else self.fm.stringWidth("W" * self.minColWidth)
            dim.width = Math.max(dim.width, strWidth)
            return dim

        # Avoid width resizes changing the GUI back and forth....
        def getPreferredSize(self):
            dim = super(self.__class__, self).getPreferredSize()
            self.maxWidth = Math.max(self.maxWidth, dim.width)
            dim.width = self.maxWidth
            return dim

```

Please don't distracted by the Jython, it's exactly the same issue in pure Java...

As you can see, this is a bog standard extension of JTextField... Nothing special at all...

See video:


https://github.com/violetlib/vaqua/assets/22958485/4c4186ab-f4bd-489a-bf80-772dd9bc85bb

**Comment by cbfiddle** [comment]
I'm not denying your experience, but I'm not seeing that behavior myself. Presumably there is something different in your environment. If you can provide a small, self-contained test program that shows the problem, I can try it out and see if I get the same results.

**Comment by yogi1967** [comment]
as I said, somewhat impossible to give you a test program. It's random. I'm aware of many others with exactly the same issue.

**Comment by yogi1967** [comment]
... can you advise... does VAQua do something with caret position and text selection?

**Comment by cbfiddle** [comment]
The selection and caret are intimately linked. See JTextComponent.select().

I found one bit of code that might be related, and I don't know what it's purpose is...
```
    protected class AquaTextFieldFocusHandler extends AquaFocusHandler {
        @Override
        public void focusLost(@NotNull FocusEvent ev) {
            super.focusLost(ev);
            if (!ev.isTemporary()) {
                Caret c = editor.getCaret();
                if (c != null) {
                    c.setDot(0);
                }
            }
        }
    }

```
I'm assuming these problems are new, so it would be helpful to look for things that you changed in this time frame.
For example, does the problem happen with the previous VAqua?
Did you start using a new machine or a new mouse/tablet?
Did you add event listeners or borders to text components?
Did you change the use of threads? (Random behavior is often caused by threading problems.)

It might be useful to comment out the event listeners and custom borders to see if that makes a difference.

Failing that, I would suggest breakpointing the paintComponent method (when this happens) and stepping through it to see why it appears to paint only one character.

Scrolling might be involved. Perhaps something is causing the scroll position to change on each keystroke.

**Comment by yogi1967** [comment]
No these issues are NOT new.. They've certainly been around for over a year (may be more).
- Certainly since a few VAQua releases back
- No my machine has not changed, other than Sonoma, same issue on that version too.
- Other platforms are OK. 
- Same issues with older Javas too.
- This Application has not changed in this area for a long time

**Comment by cbfiddle** [comment]
Well, there's not much I can do without being able to run a program that exhibits the behavior, even if it is random.
Lacking that, I need you to do some experimenting and/or debugging.

**Comment by yogi1967** [comment]
Understood... Being random it's tricky.. I was hoping you would look at the VAQua code in this area and 'spot' something.

**Comment by yogi1967** [comment]
I also have a question mark over:

`protected class AquaTextFieldFocusHandler extends AquaFocusHandler`

.. it is clearly different / new from the original Aqua code and I also don't know what it does. 

HOWEVER, after some time spent on this, I have managed to reproduce on other LAFs too. 

The exact scenario is when you use the mouse to select all text in a JTextField from right to left, then type fast. I can repro this about 75% of the time. 

It also occurs on other Java apps too. It also seems to go far back to many old Java versions. 

It doesn't occur on Windows/Linux.

So I think it's in std Java code somewhere. Perhaps mouseMovementListener or AquaCaret etc. 

Anyway, closing this. Thanks.
