### ISSUE TITLE
VAqua 12 not loading in MacOS 14 / Java 17 on aarm64

### ISSUE THREAD

**Issue by rwcope2** [violetlib/vaqua#41]
I'm unable to get VAqua 12 to load when launching from the command line. The error that I get is:

```
AquaNativeSupport: Unable to load library libvaqua.dylib: Can't load library: /var/folders/.../libvaqua13685385324360054844.dylib
Error initializing look and feel. VAqua release 12 (build 2023-10-31T23:37:24Z) not supported on this platform
```

I've tried following the advice from [this similar issue](https://github.com/violetlib/vaqua/issues/18).  I downloaded the [unbundled JavaNativeFoundation](https://github.com/weisJ?tab=packages&repo_name=JavaNativeFoundation) mentioned [violetlib.org](https://violetlib.org/share/universalbinaries.html) and placed it in ~/Library/Java/Extensions, but that didn't work.  I also tried placing it in a position relative to my working directory.  In both cases I set DYLD_FRAMEWORK_PATH accordingly, but none of that seemed to work.

Sorry, I'm not very familiar with dynamically loaded libraries.  Do you have any advice for getting VAqua to load in this circumstance?

Everything works fine on x86 Macs.

My environment:

MacOS 14.4
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode)

Thanks,  
Rob

**Comment by cbfiddle** [comment]
It is possible that DYLD_FRAMEWORK_PATH does not work running java from the command line, for security reasons.
You are more likely to succeed constructing an application bundle.

An alternative is to build VAqua and VAquaRendering from the latest sources on GitHub.
Those sources do not use JavaNativeFoundation.

**Comment by rwcope2** [comment]
Thank you, this really helpful!
