### ISSUE TITLE
Question: Can VAQua use the Mac's ability to set hidden Menu items that get shown when the user holds down the Option key?

### ISSUE THREAD

**Issue by yogi1967** [violetlib/vaqua#42]
Native AppKit code can set NSMenuItem.isAlternate... Wondering whether VAQua has a way to hook into this..? Thanks

**Comment by cbfiddle** [comment]
No. VAqua does not create native menus.

I have implemented that behavior in my own code using an AWTEventListener and a configurable JMenuItem.

**Comment by yogi1967** [comment]
Thanks
