### ISSUE TITLE
Double-click on window title doesn't zoom the window when using unified toolbar

### ISSUE THREAD

**Issue by karlvr** [violetlib/vaqua#43]
Without the unified toolbar this feature works fine.

**Comment by cbfiddle** [comment]
That’s odd. It works for me.

**Comment by karlvr** [comment]
Oh no. The worst! :-)

More investigation... double-clicking the title _text_ works, but double-clicking anywhere else in the title bar doesn't work. 

Adding/removing this line of code is the only change required to break/fix this behaviour in my app:

```java
getRootPane().putClientProperty("Aqua.windowStyle", "unifiedToolBar");
```

**Comment by cbfiddle** [comment]
That also works for me. :-)

**Comment by karlvr** [comment]
@cbfiddle heh. I'm running in Java 17... maybe you're on a different version?

**Comment by cbfiddle** [comment]
Yes, I’m using 22. If I run on 17 I see the problem.

**Comment by karlvr** [comment]
@cbfiddle thank you for trying that out! I'm closing this. Not a VAqua problem :-D Thanks for your help.
