### ISSUE TITLE
UnsatisfiedLinkError on M1 with VAqua9 when setting look and feel

### ISSUE THREAD

**Issue by kortenkamp** [violetlib/vaqua#9]
Hi,

so far we are using VAqua7 without problems. I just wanted to upgrade to VAqua9, and now I cannot even set the look and feel.

```
    [java] Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void org.violetlib.aqua.AquaUtils.registerWindowChangedAppearanceCallback(org.violetlib.aqua.AquaUtils$WindowAppearanceChangedCallback)'
     [java] 	at org.violetlib.aqua.AquaUtils.registerWindowChangedAppearanceCallback(Native Method)
     [java] 	at org.violetlib.aqua.AquaUtils.<clinit>(Unknown Source)
     [java] 	at org.violetlib.aqua.AquaNativeSupport.reportError(Unknown Source)
     [java] 	at org.violetlib.aqua.AquaNativeSupport.loadNativeSupport(Unknown Source)
     [java] 	at org.violetlib.aqua.AquaNativeSupport.load(Unknown Source)
     [java] 	at org.violetlib.aqua.AquaLookAndFeel.isSupportedLookAndFeel(Unknown Source)
     [java] 	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:577)
     [java] 	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:638)
     [java] 	at de.cinderella.toolkit.OSHelper.setupVAqua(OSHelper.java:117)
```

This might be a problem of running the whole thing on an M1 machine, but I had no trouble with VAqua7 before.

Next I thought that I could have a look into the source and maybe build a universal library myself, but I am running into problems there as well. I could not find any build instructions, `java_home` does not exists on my machine at all (I could work around that) and still I do not know what to do to build the library, as it is not sufficient to just run `ant` with `release/build.xml`  – can you give a hint? 

Thanks! Ulli

**Comment by kortenkamp** [comment]
Maybe I should add that I have no experience using maven, which could be a problem… I installed maven using homebrew, but running ant just tells me:

```
M1-UK~/Documents/Versioned/vaqua/release(m1|✚1) % ant
Buildfile: /Users/ulli/Documents/Versioned/vaqua/release/build.xml

clean:

resolve-maven:

BUILD FAILED
/Users/ulli/Documents/Versioned/vaqua/release/build.xml:72: Problem: failed to create task or type antlib:org.apache.maven.resolver.ant:resolve
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
No types or tasks have been defined in this namespace yet

This appears to be an antlib declaration.
Action: Check that the implementing library exists in one of:
        -/opt/homebrew/Cellar/ant/1.10.9/libexec/lib
        -/Users/ulli/.ant/lib
        -a directory added on the command line with the -lib argument


Total time: 0 seconds
M1-UK~/Documents/Versioned/vaqua/release(m1|✚1) %
```

**Comment by cbfiddle** [comment]
java_home is in /usr/libexec

I had to remove the path because for a while it was broken on macOS 11.

running ant on release/build.xml is the right idea

**Comment by kortenkamp** [comment]
Ok... I am somewhat successful, but still I cannot compile the Java sources. I installed a Java 8 JVM that includes rt.jar, and I have a 9+ javac compiler. Still, I get:

```
M1-UK~/Documents/Versioned/vaqua/release(m1|✚1) % ant
Buildfile: /Users/ulli/Documents/Versioned/vaqua/release/build.xml

clean:

resolve-maven:
[resolver:resolve] Resolving artifacts

resolve:

compile8:
    [mkdir] Created dir: /Users/ulli/Documents/Versioned/vaqua/release/out/classes
    [mkdir] Created dir: /Users/ulli/Documents/Versioned/vaqua/release/out/headers
    [javac] Compiling 251 source files to /Users/ulli/Documents/Versioned/vaqua/release/out/classes
    [javac] /Users/ulli/Documents/Versioned/vaqua/src/org/violetlib/aqua/AquaButtonBorder.java:48: error: cannot find symbol
    [javac] import org.violetlib.jnr.aqua.AquaUIPainter.GenericButtonWidget;
    [javac]                                            ^
    [javac]   symbol:   class GenericButtonWidget
    [javac]   location: interface AquaUIPainter
    [javac] /Users/ulli/Documents/Versioned/vaqua/src/org/violetlib/aqua/AquaToggleButtonBorder.java:17: error: cannot find symbol
    [javac] import org.violetlib.jnr.aqua.AquaUIPainter.GenericButtonWidget;
    [javac]                                            ^
    [javac]   symbol:   class GenericButtonWidget
    [javac]   location: interface AquaUIPainter
...
```

Again, any hint that can help me to successfully compile?

Thanks
Ulli

**Comment by cbfiddle** [comment]
It needs to know where VAquaRendering.jar is. Set renderingLibraryJAR.

**Comment by kortenkamp** [comment]
> It needs to know where VAquaRendering.jar is. Set renderingLibraryJAR.
> […](#)

Sorry, I am confused, and it all might be caused by my ignorance for maven. However, in the meantime I successfully created VAquaRendering.jar using the `jnr` repository, but I do not find any way to tell vaqua to use it. Also, it seems to me that either maven or ivy is used to generated the classpath, and I would expect that the VAquaRendering.jar is included automagically through the `<dependency coords="org.violetlib:jnr:${jnrVersion}"/>`.

Sorry for all those stupid questions, all I want to do is to create VAqua9.jar from scratch, in order to be able to compile the native libraries as universal binaries...

**Comment by cbfiddle** [comment]
Yes, I think I gave you obsolete advice. Sorry about that.

If you want Maven to find your own local JAR, it has to be in the local Maven repo. I can’t give you instructions from memory, but you should be able to find it in the Maven docs.
